### PR TITLE
Use containers ..

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
@enygma now the build is having a different error though ;-) . Sorry not having idea on it.

> 1) Psecio\Gatekeeper\GatekeeperTest::testGetUserThrottle
> Trying to get property of non-object

May be you can easily fix.

**Comment by enygma** [comment]
So I'm curious....why does this change things? Is there some magic the Travis-CI container uses sudo for?

**Comment by harikt** [comment]
@enygma http://docs.travis-ci.com/user/workers/container-based-infrastructure/

**Comment by harikt** [comment]
There is also another article on the subject : http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by enygma** [comment]
works for me - merging! thanks.

**Comment by harikt** [comment]
cool.

@enygma I was looking at the gatekeeper-ui library and have a question / suggestion. Will open there.

**Pull request merged**
