### PR TITLE
Initial pgsql support

### PR DESCRIPTION
**Pull request by Awnage**
Also changes to timestamp instead of datetime to make sure things are timezone independent. Would this bork other areas of the code?

### CODE REVIEW

**Comment by Awnage** [comment]
NVM. MySQL's timestamp still does things grossly different from PostgreSQL.

**Comment by Awnage** [comment]
Would be better if phinx did the translation from mysql:datetime to phinx:timestamp

**Comment by enygma** [comment]
:( too bad....would have been nice to have that cross-db support. I wonder if there's other tools out there that may support it a bit better.

**Comment by Awnage** [comment]
I would need to go through a lot more code than I have time right now to make sure it worked correctly. :(

**Comment by enygma** [comment]
d'oh - well, I appreciate the time spent on it already!

**Pull request closed without merging**
